spring:
  application:
    name: ${SPRING_APPLICATION_NAME:contragent-datastore}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/schema_manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate.format_sql: ${FORMAT_SQL:true}

clickhouse:
  url: ${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123}
  username: ${CLICKHOUSE_USERNAME:default}
  password: ${CLICKHOUSE_PASSWORD:}
  database: ${CLICKHOUSE_DATABASE:schema_data?compress=0}

minio:
  access-key: ${MINIO_ACCESS_KEY:ROV5I9vWHvB16zDlK6Q3}
  secret-key: ${MINIO_SECRET_KEY:6w6BJhVS8fdSl0yjsIeXPBvvlrZ3xG4ji2SaeDru}
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
