version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schema_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_datamanager_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.5
    container_name: clickhouse_db
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  minio:
    image: minio/minio:latest
    container_name: minio_server
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # Access MinIO via the web UI on port 9000
      - "9001:9001"  # MinIO Console port for monitoring
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"

volumes:
  postgres_datamanager_data:
  clickhouse_data:
  minio_data:
